# Generated by Django 4.1 on 2022-08-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_product_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_of_entry',
            field=models.DateField(null=True),
        ),
    ]
