# Generated by Django 4.1 on 2022-08-29 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_product_time_of_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_of_entry',
        ),
    ]
