# Generated by Django 4.1 on 2022-09-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='exclusive_products',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
