# Generated by Django 4.1.1 on 2022-09-22 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0014_product_product_pic2_product_product_pic3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.IntegerField()),
                ('pincode', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('payment_mode', models.CharField(choices=[('cod', 'Cash on delivery'), ('gpay', 'google pay on 123')], max_length=10, null=True)),
                ('grandtotal', models.IntegerField()),
                ('order_date', models.DateField(auto_now_add=True)),
                ('order_update_date', models.DateField(auto_now=True)),
                ('order_status', models.CharField(choices=[('received', 'Order Received'), ('process', 'order in process'), ('shipped', 'order shipped'), ('delivered', 'order delivered'), ('pending', 'Order pending'), ('cancelled', 'order cancelled')], default='received', max_length=10, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('total_cost', models.IntegerField()),
                ('orderno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
    ]
